### ISSUE TITLE
Error: Closed relay. Unknown stream

### ISSUE THREAD

**Issue by diachen** [fiddyschmitt/File-Tunnel#10]
Errors are appearing during working of the tunnel, and the connection is down (version 2.0.0 and v1.0.6 too)
Closed relay. Unknown stream -> 1.dat
Closed relay. 2.dat -> Unknown stream

**Comment by fiddyschmitt** [comment]
Thanks Dia, I'll look into it.

What client/server are you trying to bridge?

What File Tunnel commands are you running?

What is the full console output of the File Tunnel?

**Comment by diachen** [comment]
hi, thank you for your quick reply!

  on terminal machine (win server 2012 r2) i run:
ft.exe --tcp-listen 127.0.0.1:7778 --read "\\tsclient\c\Temp\shtrih1.dat" --write "\\tsclient\c\Temp\shtrih2.dat"
  on another machine (win10):
ft.exe --write "C:\Temp\shtrih1.dat" --read "C:\Temp\shtrih2.dat" --tcp-connect 192.168.137.111:7778

data is sent from terminal machine to win10

  output on terminal machine
06.06.2024 17:43:43: Counterpart: Online    Rx: 0 b/s        Tx: 8 b/s
06.06.2024 17:43:43: [shtrih1.dat] Counterpart asked to tear down connection 32
06.06.2024 17:43:43: [shtrih1.dat] Counterpart asked to tear down connection 31
06.06.2024 17:43:43: [shtrih1.dat] Counterpart asked to tear down connection 30
06.06.2024 17:43:43: Closed relay. Unknown stream -> shtrih2.dat
06.06.2024 17:43:43: Closed relay. Unknown stream -> shtrih2.dat
06.06.2024 17:43:43: Accepted connection from 127.0.0.1:63556
06.06.2024 17:43:43: Closed relay. Unknown stream -> shtrih2.dat
06.06.2024 17:43:43: Closed relay. Unknown stream -> shtrih2.dat
06.06.2024 17:43:43: Closed relay. shtrih1.dat -> Unknown stream
06.06.2024 17:43:43: Closed relay. Unknown stream -> shtrih2.dat
06.06.2024 17:43:43: Closed relay. Unknown stream -> shtrih2.dat
06.06.2024 17:43:43: Closed relay. shtrih1.dat -> Unknown stream
06.06.2024 17:43:43: Closed relay. shtrih1.dat -> Unknown stream
06.06.2024 17:43:43: Closed relay. shtrih1.dat -> Unknown stream
06.06.2024 17:43:43: Closed relay. shtrih1.dat -> Unknown stream
06.06.2024 17:43:43: Closed relay. shtrih1.dat -> Unknown stream
06.06.2024 17:43:45: Counterpart: Online    Rx: 0 b/s        Tx: 8 b/s        RTT: 1 124 ms
06.06.2024 17:43:46: Counterpart: Online    Rx: 8 b/s        Tx: 0 b/s        RTT: 3 ms

  output on win10
06.06.2024 17:43:43: Connected to 192.168.137.111:7778
06.06.2024 17:43:43: Closed relay. Unknown stream -> shtrih1.dat
06.06.2024 17:43:43: Closed relay. shtrih2.dat -> Unknown stream
06.06.2024 17:43:43: Closed relay. Unknown stream -> shtrih1.dat
06.06.2024 17:43:43: Closed relay. shtrih2.dat -> Unknown stream
06.06.2024 17:43:43: Connected to 192.168.137.111:7778
06.06.2024 17:43:43: Connected to 192.168.137.111:7778
06.06.2024 17:43:43: Counterpart: Offline   Rx: 0 b/s        Tx: 0 b/s        RTT: 1 110 ms
06.06.2024 17:43:44: Counterpart: Online    Rx: 16 b/s       Tx: 8 b/s        RTT: 8 ms
06.06.2024 17:43:49: Closed relay. Unknown stream -> shtrih1.dat

**Comment by fiddyschmitt** [comment]
Thanks! Your commands look good.

Does the RTT go above 3,000 ms?

**Comment by diachen** [comment]
Both computers are located in local network (1 Gb/s, via RDP). With version 2.1.0 all problems are gone. Thanx a lot!

**Comment by fiddyschmitt** [comment]
Awesome to hear!! Thanks Dia!
