### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by eylandoo** [fiddyschmitt/File-Tunnel#17]
hello
I have a request from you. 
I want a basic tutorial to tunnel one port to another server port  

Please brotherly tell me this prototype on two Ubuntu Linux, for example.

Sincerely

**Comment by fiddyschmitt** [comment]
Hey,

- Download `ft-linux-x64` from [here](https://github.com/fiddyschmitt/File-Tunnel/releases).
- On Machine A, run: `./ft-linux-x64 -L 0.0.0.0:5000:192.168.1.5:6000 --write /mnt/shared/1.dat --read /mnt/shared/2.dat`
- On Machine B, run: `./ft-linux-x64 --read /mnt/shared/1.dat --write /mnt/shared/2.dat`

Now any computer can connect to Machine A on port 5000, and it will automatically be forwarded through Machine B and onto `192.168.1.5:6000`.

`/mnt/shared/` is a shared folder on the network that both machines have access to, typically over SMB or NFS.

Cheers,
Fidel
