### ISSUE TITLE
Use memory-only streams rather than shared files on disk

### ISSUE THREAD

**Issue by kimmccoy** [fiddyschmitt/File-Tunnel#30]
Ensuring local disks are shared and a folder is suitable is a bit of a pain. Would it be possible to use in-memory streams and not files on disk?

I have successfully used this below project for years which sends & receives data via RDP channel streams without buffering to disk files first.
https://www.codeproject.com/Articles/16374/How-to-Write-a-Terminal-Services-Add-in-in-Pure-C

**Comment by fiddyschmitt** [comment]
Thanks Kim!

That is very interesting. There are other programs such as [rdp-tunnel](https://github.com/NotMedic/rdp-tunnel) which use Virtual Channels for tunneling TCP.

The focus of File Tunnel is to generically support tunneling over files. The fact that it allows tunneling through RDP as well was just a happy coincidence.

Cheers,
Fidel

**Comment by kimmccoy** [comment]
I see now. I didn't realise the focus on using files as a means to many ends even though you called it File-Tunnel ;)
Works great anyway. Very nice project.

**Comment by fiddyschmitt** [comment]
:D thanks so much Kim!
