### ISSUE TITLE
How to compile for linux?

### ISSUE THREAD

**Issue by Tang-Haojin** [fiddyschmitt/File-Tunnel#32]
Hi, thanks for the great work!

I wonder how can I compile this project myself for a linux platform? I can only find a pre-built linux binary but I also want to try myself to build for my own linux. (Because my runtime env is not compatible with the shared library version required by the pre-built one.)

**Comment by fiddyschmitt** [comment]
Thanks @Tang-Haojin!

To compile in Linux:

1. Install .NET in Linux. Instructions [here](https://learn.microsoft.com/en-us/dotnet/core/install/linux?WT.mc_id=dotnet-35129-website)
2. Download and unzip the source:
```
wget "https://github.com/fiddyschmitt/File-Tunnel/archive/refs/heads/master.zip"
unzip master.zip
cd "File-Tunnel-master"
```
3. Compile
`dotnet publish -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true -p:useapphost=true`

The built binary will be stored in:
`ft/bin/Release/net8.0/linux-x64/publish`

Cheers,
Fidel

**Comment by Tang-Haojin** [comment]
It works. Thank you~
