### ISSUE TITLE
Broken Pipe when purge mechanism is triggered.

### ISSUE THREAD

**Issue by l0042158** [fiddyschmitt/File-Tunnel#7]
First of all, thank you for providing this.

I have run into an issue with the purge mechanism.
Every time the purge mechanism is triggered I run into a broken pipe message from rsync or similar programs which can use more than just a very small amount of bandwidth.

![image](https://github.com/fiddyschmitt/TCP-over-File/assets/73488709/c44ed786-79fd-4294-902e-311b7fbe8d44)

![image](https://github.com/fiddyschmitt/TCP-over-File/assets/73488709/021705b5-4ef9-4a8c-9c43-3d3aa594008d)

![image](https://github.com/fiddyschmitt/TCP-over-File/assets/73488709/9121ef5b-4ad5-4656-ba68-ded54bc05497)

**Comment by Lennart00** [comment]
I don't really know how to fix this, but I would like to try either disabling the purge mechanism or changing it to trigger at a much higher value.

**Comment by Lennart00** [comment]
One more idea from my side is that some kind of rate limitation could be maybe useful, if running at unlimited speeds is causing unreliability due to lock ups and race conditions.

**Comment by Lennart00** [comment]
Restartting the rsync task in a while loop until it finally transfers some more over now cause this to happen:

5/2/2024 3:56:25 PM: Could not read command at file position 0. [\\tsclient\d\Temp\1.dat]

This was in red and the program exited after this.

**Comment by Lennart00** [comment]
I am not sure where to put this. It's probably a separate issue, but sometimes the remote Hosts ft.exe needs to receive a ctrl-c interrupt, before the connection is established after i restart both sides.

**Comment by Lennart00** [comment]
The dat files have to be regularly deleted in my testing for the program to be able to run correctly again after the scenarios described above.

I have made it work now partially. After deleting the dat file and enabling rate limitation to about 40 kb per second it works now without failing for now.

**Comment by Lennart00** [comment]
Running cat on /dev/zero on the remote host does not seem to be causing the issues faced the other way around when congesting the tunnel.

**Comment by fiddyschmitt** [comment]
Thanks Lennart! Epic info, thanks!

I'll add command line args to:
- Turn off purging
- Control size at which to purge
- Control rate

I'll investigate the other things as well, by testing with rsync. Could you please let me know the rough composition of what you are rsycning? Large file? Small files? Lots of folders?

Thanks again!
Fidel

**Comment by fiddyschmitt** [comment]
[v1.0.3](https://github.com/fiddyschmitt/TCP-over-File/releases/tag/v1.0.3) now lets you control the purge size:

Purge at 1 MB:
`--purge-size 1048576`

Disable purging:
`--purge-size 0`

**Comment by Lennart00** [comment]
Thank you very much.
Disabling the purge mechanism has solved the problem with the broken pipe for me so far in my initial testing.
Something like this works now:
![image](https://github.com/fiddyschmitt/TCP-over-File/assets/73488709/305cad91-8f60-4f56-8ae1-ba33808449ce)
This kept running without issues for minutes.

Example running with the default purging mechanism:
![image](https://github.com/fiddyschmitt/TCP-over-File/assets/73488709/7c5edf70-d774-46df-aada-88a1ae0df312)
Failed after 3 seconds.

I am still in the process of making this work for a vscode remote dev environment and will report back on that.

Best regards
Lennart

**Comment by Lennart00** [comment]
I think this is the simplest test for saturating the bandwidth pretty much:

`cat /dev/zero | ssh ftWslHost 'cat > zeroOut'`

Putting pv in between allows to see the throughput.

`cat /dev/null | pv | ssh ftWslHost 'cat > nullOut'`

**Comment by fiddyschmitt** [comment]
Awesome!! Thank you. Will try.

**Comment by Lennart00** [comment]
I made a minor mistake with the command:

`( pv | ssh ftWslHost 'cat > /dev/null' ) < /dev/zero`

pv was not receiving the input the way i wrote this earlier. I had to upgrade my system to actually run in :D

**Comment by Lennart00** [comment]
I have successfully used your Program to connect to my target machine via vscode remote. This is exactly what i need for my use case.
The connection seems to be very stable.

Thank you very much

Best regards
Lennart o7

**Comment by fiddyschmitt** [comment]
Hi @Lennart00,

If you get a chance, could you please try v1.0.4?

The purge functionality should work more reliably now.

Thanks,
Fidel

**Comment by Lennart00** [comment]
Hi Fidel,

I will give it a try and report back to you.

Best regards,
Lennart

**Comment by fiddyschmitt** [comment]
Nice! Thanks for following up Lennart :D

A ramdisk would work nicely. I wouldn't be very concerned about deterioration of the drive though, as these days they have really good wear-levelling and you'd have to write hundreds of TBs before you'd see any issues. Still curious to hear how it goes though :)

**Comment by Lennart00** [comment]
Hi Fidel,

Thanks again for the update increasing the throughput.
The ramdisk combined with your news version increased the throughput for my setup to this value:
![image](https://github.com/fiddyschmitt/TCP-over-File/assets/73488709/3e10844d-a5b1-472a-b318-cab0a4a50a1c)
There is a vpn between me and the target additionally, so i don't know what the limiting factor is.

Best regards,
Lennart
